# Generated by Django 6.0.4 on 2026-04-24 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cheap', 'Дешевые'), ('middle', 'Средние'), ('expensive', 'Дорогие')], default='cheap', max_length=20)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=255, verbose_name='Название оружия')),
                ('skin_name', models.CharField(max_length=255, verbose_name='Название скина')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rarity', models.CharField(choices=[('blue', 'Mil-Spec'), ('purple', 'Restricted'), ('pink', 'Classified'), ('red', 'Covert'), ('gold', 'Exceedingly Rare')], default='blue', max_length=10)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropped_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.item')),
            ],
        ),
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.DecimalField(decimal_places=4, help_text='Шанс выпадения в %', max_digits=8)),
                ('range_from', models.IntegerField(blank=True, null=True)),
                ('range_to', models.IntegerField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.item')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='items',
            field=models.ManyToManyField(through='cases.CaseItem', to='cases.item'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
