# Generated by Django 6.0.4 on 2026-04-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image_url',
            field=models.URLField(blank=True, max_length=3000),
        ),
    ]
