# Generated by Django 6.0.4 on 2026-04-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
