# Generated by Django 6.0.5 on 2026-05-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.IntegerField(),
        ),
    ]
