# Generated by Django 6.0.5 on 2026-05-29 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_price_alter_item_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('result_value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_results', to='cases.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
